# Generated by Django 4.0.4 on 2022-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('r_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField()),
                ('time_stamp', models.CharField(max_length=8)),
                ('seq_no', models.IntegerField()),
                ('instruction', models.CharField(max_length=200)),
            ],
        ),
    ]
