# Generated by Django 4.0.4 on 2022-07-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_recipe_instruction_recipeinstruction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='r_id',
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipe'),
        ),
    ]
