# Generated by Django 4.0.4 on 2022-07-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_item_remove_recipe_r_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeinstruction',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.recipe'),
        ),
    ]
